name: Greetings

on: [pull_request, issues]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@1115336c217415b3a53d9e4c5e3170e70a6c6a46 # v1.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome! Thank you for your first issue contribution. :)'
        pr-message: 'Welcome! Thanks for your first pull!'
